---

  - name: Save the db_create script
    template: 
      src: ../templates/db_create.js.j2 
      dest: /tmp/db_create.js

  - name: Run the db_create script
    shell: >
      mongo
      --host {{ server_fqdn }}
      --port {{ rs_port }}
      --ssl
      --sslPEMKeyFile {{ cert_path.chain.remote }}
      --sslCAFile {{ cert_path.intermediate.remote }}
      < /tmp/db_create.js
    register: result

  - name: Kill the db_create script
    file: 
      dest: /tmp/db_create.js
