---
- name: kill logs
  include_tasks: kill-logs.yml

- name: Status of data directory
  stat:
    path: "{{ mount_base }}"
  register: stat_mnt

- name: Delete storage_path directory
  file:
    path: "{{ storage_path }} "
    state: absent
  become: true

- name: Delete mounted directory
  file:
    path: "{{ mount_path }}"
    state: absent
  become: true
  when: stat_mnt.stat.isdir is defined and stat_mnt.stat.isdir

- name: Create db dir, basic
  file:
    path: "{{ mount_path }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: "0755"
  when: stat_mnt.stat.isdir is not defined or not stat_mnt.stat.isdir
  become: true

- name: Create db dir, mounted
  file:
    path: "{{ mount_path }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: "0755"
  when: stat_mnt.stat.isdir is defined and stat_mnt.stat.isdir
  become: true

- name: Create link, if needed
  file:
    src: "{{ mount_path }}"
    dest: "{{ storage_path }}"
    state: link
    owner: mongodb
    group: mongodb
    mode: "0755"
  when: stat_mnt.stat.isdir is defined and stat_mnt.stat.isdir
  become: true
